# This is a basic workflow to help you get started with Actions

name: github-input

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#   push:
#     branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      name1:
        description: 'enter the value of a'     
        required: true
        default: '10'
      name2:
        description: 'enter the value of b'     
        required: true
        default: '20'
env:
  number1: ${{github.events.inputs.name1}}
  number2: ${{github.events.inputs.name2}} 
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
     

      # Runs a set of commands using the runners shell
      - name: Run a script for adding two numbers
        run: |
          python one.py $number1 $number2
          
